Remove signature key indirection
openmls/openmls pull request #1117
Opened 2022-11-23 20:44 UTC by raphaelrobert

This PR fixes #1088.

It introduces the following changes:
 - Message processing becomes easier because we can now drop the parsing step. `MlsMessageIn` can now be processed directly.
 - `ProcessedMessage` now also consistently exposes header values (epoch, sender, aad, etc.). The content is exposed through `.content()` or `.into_content` and is equivalent to the old enum that has now been renamed to `ProcessedMessageContent`.
 - The API change revealed that most ValSem positive tests were not entirely correct (as well as a few other tests), this has now been fixed.

The first commit contains the relevant code changes, the other commits only contain the adjustments to the new API and the test fixes.

2022-11-24 08:08 UTC, kkohbrok requested changes
Thanks for digging through all this churn. Looks good to me in general, just a few nits.

2022-11-24 08:08 UTC, kkohbrok commented on openmls/tests/test_mls_group.rs
> +        //let sender = processed_message
This can probably go.

2022-11-24 22:02 UTC, raphaelrobert commented on openmls/src/group/tests/external_proposal.rs
> -            UnverifiedMessageError::InvalidSignature
As discussed offline, this test was repetitive and broken (which was only discovered with the new API).

2022-11-25 09:19 UTC, kkohbrok approved these changes

2022-11-25 09:42 UTC, merged