refactor/correctness: Move `GroupInfo` into own module and tighten-up serialization.
openmls/openmls pull request #1206
Opened 2023-01-18 13:32 UTC by duesee

Over the course of preparing a short blog post about validation in OpenMLS I cleaned up `GroupInfo` a bit.

This PR does the following:

* Move `GroupInfo` (and all related types) into a new `group_info` module.
* Make it so that `VerifiableGroupInfo` does not (unnecessarily) derive `Serializable`. `Serializable` is test-gated now.
* `#[derive(TlsSerialize, TlsSize)]` for `GroupInfo` instead of implementing it.
* Remove unused `test_pgs.rs`.

2023-01-20 16:19 UTC, franziskuskiefer requested changes
Thanks, generally looks good two me with a nit and a question.

Do we really want to delete `test_pgs.rs`? The names etc. aren't right anymore but did you check that the tests aren't useful?

2023-01-20 22:20 UTC, duesee commented on openmls/src/framing/message_in.rs
> +//! [`PrivateMessage`], [`KeyPackage`], [`Welcome`] or [`crate::messages::group_info::GroupInfo`]) can be
That's nicer, yeah :+1:

2023-01-20 22:23 UTC, duesee commented
`test_pgs.rs` is an empty file. Probably a leftover from another PR or merge. But let me take that as an opportunity to re-check if we really test what we want.

2023-01-23 11:34 UTC, duesee commented on openmls/src/framing/message_in.rs
> +//! [`PrivateMessage`], [`KeyPackage`], [`Welcome`] or [`crate::messages::group_info::GroupInfo`]) can be
Done in 821f20b76c73b2a5e9f937221041cac261120d52

2023-01-23 11:42 UTC, duesee commented
> But let me take that as an opportunity to re-check if we really test what we want.

The test were moved into `test_export_group_info.rs` in https://github.com/openmls/openmls/commit/b56883aaec03a3c64983b6ea44576530785554d9#diff-9cae41c82a5e5d4f72878ed55cf19a4580d42b6b3e87a2a2a1eb1701100e82ff. I also think they suffice for now (export + verify signature).

2023-01-23 11:43 UTC, duesee commented
Commited some unrelated stuff by accident and reverted.

2023-01-24 13:02 UTC, franziskuskiefer approved these changes
Thanks

2023-01-24 13:02 UTC, merged