feat: Return group info on stage commit
openmls/openmls pull request #1211
Opened 2023-01-19 09:07 UTC by augustocdias

Closes #1150 

First I'm sorry for the big PR. The reason is that because of the signature change, a lot of tests were affected. 

The biggest use case for this feature is to return the `GroupInfo` in order to make a join with external commit. Docs were added to the book with an example explaining how to do it.

We have opted for returning an optional since this only makes sense if the the ratchet tree is required. OpenMls doesn't support specifying required capabilities as of now (should we open a new issue for that?) and the default behavior in the `RequiredCapabilitiesExtension` is to support everything as can be seen [here](https://github.com/openmls/openmls/blob/main/openmls/src/extensions/required_capabilities.rs#L79-L91). For that reason we opted for checking the `use_ratchet_tree_extension` instead.

We've added a test to make sure that the returned `GroupInfo` can be used to call `join_by_external_commit` and changed the rust docs in the functions that had their signature changed.

2023-01-20 08:03 UTC, kkohbrok requested changes
Thanks for picking this up! Just a few nits, then this is good to go.

2023-01-20 08:03 UTC, kkohbrok commented on openmls/tests/test_external_commit.rs
> +    let mut alice_group = {
While you're at it, do you want to pull this part out into a function? Seems like it's the same setup for all tests in this file.

2023-01-20 08:03 UTC, kkohbrok commented on openmls/tests/test_external_commit.rs
> +    alice_group.merge_pending_commit().unwrap();
Maybe it would be worth to also return the GroupInfo when creating a new group? We don't have to do it in this PR, though.

2023-01-20 09:47 UTC, augustocdias commented on openmls/src/group/mls_group/updates.rs
> +    /// The [GroupInfo] is [Some] if the group has the `RatchetTree` required capability.
I see. I probably got confused because the `ExtensionType` is in the `RequiredCapabilitiesExtension` and the `RatchetTree` is a variant there.

2023-01-20 09:49 UTC, augustocdias commented on openmls/src/group/core_group/create_commit.rs
> +        // TODO: check for the required capabilities if RatchetTree is supported and return the
If the RatchetTree is always supported, I think we should just leave with the flag.

2023-01-20 09:57 UTC, augustocdias commented on openmls/src/group/core_group/create_commit.rs
> +        // TODO: check for the required capabilities if RatchetTree is supported and return the
https://github.com/openmls/openmls/issues/1213

2023-01-20 10:10 UTC, augustocdias commented on openmls/src/group/core_group/create_commit.rs
> +        // TODO: check for the required capabilities if RatchetTree is supported and return the
I removed the comment

2023-01-20 10:36 UTC, augustocdias commented
@kkohbrok after merging main into my branch I started having clippy warning about type complexity in the results with tuples/triples. Should I create a specific type for `(MlsMessageOut, Option<MlsMessageOut>, Option<GroupInfo>)` for example or just add the allow derive for clippy?

2023-01-23 07:04 UTC, kkohbrok commented
I would say for the tests, the `allow` is okay, but in the actual library it would be good to have a dedicated type. While you're changing the API anyway, I it would make sense to have all functions return an `MlsMessageOut` containing a `GroupInfo` rather than the bare `GroupInfo`. That would be more in line with what we currently do e.g. with `Welcome` messages.

2023-01-23 08:27 UTC, augustocdias commented
@kkohbrok While I agree that it makes sense I think it would be a bit weird since we have already an enum there with a variant containing the `GroupInfo`.  Maybe create an enclosing type? Or refactor the body from the MlsMessageOut?

2023-01-23 13:57 UTC, kkohbrok approved these changes
Alright, let's get this in!

2023-01-23 14:00 UTC, merged