update credentials & introduce signer
openmls/openmls pull request #1222
Opened 2023-01-24 17:06 UTC by franziskuskiefer

TBD

2023-01-26 07:52 UTC, franziskuskiefer commented on openmls/src/key_packages/mod.rs
> -        }
There is no ciphersuite in the credential anymore so we can't check anything.

2023-01-26 11:31 UTC, kkohbrok requested changes
This is a big one. Thanks pushing through the whole thing! 

I made a general pass, but ignored a bunch of the tests. Let's get the main story straight, then I'll take a closer look at the tests, although I expect that they are mostly churn plus some refactoring.

2023-01-26 11:31 UTC, kkohbrok commented on openmls/src/group/mls_group/updates.rs
> +        // let old_credential = self.credential()?;
snip?

2023-01-26 11:31 UTC, kkohbrok commented on openmls/src/key_packages/mod.rs
> +            self.leaf_node().signature_key().clone(),
Maybe not for this PR, but we should really try to use OpenMlsSignaturePublicKey everywhere.

2023-01-26 11:31 UTC, kkohbrok commented on openmls/src/messages/mod.rs
> +    //           Get in when kat's are in again.
Add link to #1051? There are a few others like this.

2023-01-26 11:31 UTC, kkohbrok commented on openmls/src/treesync/node/leaf_node.rs
> +    pub fn updated<KeyStore: OpenMlsKeyStore>(
Do we actually need this function in the public API? Couldn't we instead call `self_update` and have it generate an updated leaf node for us?

2023-01-27 08:08 UTC, kkohbrok requested changes
Almost there. Just a few more nits, then this is good to go.

2023-01-27 08:08 UTC, kkohbrok commented on openmls/src/group/tests/test_proposal_validation.rs
> +    //           key any more.
Can you create an issue for this, since this effectively disables this test?

2023-01-27 12:22 UTC, kkohbrok approved these changes
🚢 it!

2023-01-27 12:48 UTC, merged