chore/docs: Improve `Debug`ing (+ chore)
openmls/openmls pull request #1277
Opened 2023-02-15 11:47 UTC by duesee

It is useful for debugging to `Debug`-print `GroupSecrets`. Thus, I implemented it quickly.

2023-02-15 11:54 UTC, duesee commented on openmls/src/messages/mod.rs
>      pub(crate) joiner_secret: JoinerSecret,
This is a wrapper of `Secret` and thus would be printed as "<redacted>" during non`crypto-debug` builds.

2023-02-15 11:56 UTC, duesee commented on openmls/src/ciphersuite/secret.rs
> -#[derive(Clone, Debug, Serialize, Deserialize, Eq)]
This should not have derived `Debug` to not accidentally leak the `value`.

2023-02-15 17:59 UTC, duesee commented
Sorry for the force-push. Committed on the wrong branch.

2023-02-15 18:38 UTC, franziskuskiefer requested changes
Thanks, lgtm with one nit.

2023-02-15 18:38 UTC, franziskuskiefer commented on openmls/src/ciphersuite/secret.rs
> +        ds.field("value", &"<redacted>");
We print `***` for private values so far. Let's stick to that here as well.

2023-02-16 09:14 UTC, franziskuskiefer submitted a review, later dismissed
Thanks.
There's a conflict that needs resolving.

2023-02-16 09:53 UTC, franziskuskiefer approved these changes

2023-02-16 09:56 UTC, merged