interop: Process Welcome test vectors.
openmls/openmls pull request #1288
Opened 2023-02-21 10:57 UTC by duesee

The first commits are work towards processing the test vectors as they are. For this, I needed to factor out a few methods in order to not "reimplement" the logic from `new_from_welcome`.

2023-02-22 15:00 UTC, raphaelrobert requested changes
Thanks for the PR! Just some nits

2023-02-22 15:00 UTC, raphaelrobert commented on openmls/src/group/core_group/kat_welcome.rs
> +use openmls_rust_crypto::OpenMlsRustCrypto;
Can you add a markdown header like in the other test vectors?

(from here: https://github.com/mlswg/mls-implementations/blob/main/test-vectors.md#welcome)

2023-02-23 15:11 UTC, raphaelrobert approved these changes

2023-02-23 16:31 UTC, duesee commented
Ah, sorry for the force push. It seems I screwed up something during merge conflict resolution. On the good side we have a cleaner commit history now.

2023-02-27 09:54 UTC, kkohbrok submitted a review, later dismissed

2023-02-27 10:17 UTC, kkohbrok approved these changes

2023-02-27 10:42 UTC, merged