interop: Update key schedule.
openmls/openmls pull request #1312
Opened 2023-03-06 17:31 UTC by duesee

2023-03-06 17:32 UTC, duesee commented on openmls/src/schedule/mod.rs
> +        let secret = epoch_secret.secret.derive_secret(backend, "exporter")?;
Good that we do interop... 🙈

2023-03-06 20:05 UTC, franziskuskiefer requested changes
Thanks. The actual change looks good to me. But I'm not sure where that mlspp tv is coming from. There should be only one tv.

2023-03-06 20:05 UTC, franziskuskiefer commented on openmls/src/schedule/kat_key_schedule.rs
> +        read("test_vectors/mlspp/key-schedule.json"),
Where is this coming from? There should be only one test vector by now.

2023-03-07 10:26 UTC, franziskuskiefer approved these changes
Thanks

2023-03-07 10:26 UTC, merged