interop: Implement "TreeKEM".
openmls/openmls pull request #1323
Opened 2023-03-13 16:36 UTC by duesee

2023-03-14 09:40 UTC, franziskuskiefer requested changes
Thanks, a few nits and some questions in the test vector.

2023-03-14 09:40 UTC, franziskuskiefer commented on openmls/src/binary_tree/array_representation/treemath.rs
> +    pub(crate) fn from_tree_index(node_index: u32) -> Self {
I know that this might have been me. But can we keep these functions a little more local?

2023-03-14 09:40 UTC, franziskuskiefer commented on openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
> +        // XXX: Update GroupContext.
What about this todo?

2023-03-14 09:40 UTC, franziskuskiefer commented on openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
> +        // Create a new UpdatePath new_update_path, using ratchet_tree, leaves[i].signature_priv, and the GroupContext computed above.
Can you break this line to make it easier to read?

2023-03-14 09:40 UTC, franziskuskiefer commented on openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
> +            // XXX: Update own leaf.
Todo?

2023-03-14 09:40 UTC, franziskuskiefer commented on openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
> +            // XXX: Update GroupContext.
Todo?

2023-03-14 09:40 UTC, franziskuskiefer commented on openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
> +fn apply_update_path<'a>(
So this is used only once now? It could be inlined then as well. But feel free to keep it here.

2023-03-14 09:40 UTC, franziskuskiefer commented on openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
> +    for test in tests.into_iter().take(1) {
You run only one test?

2023-03-15 15:16 UTC, duesee commented on openmls/src/ciphersuite/hpke.rs
> +    #[cfg(feature = "crypto-debug")]
Nice!

2023-03-15 16:12 UTC, franziskuskiefer approved these changes
Thanks, let's get this in.

2023-03-15 16:12 UTC, franziskuskiefer commented on openmls/src/ciphersuite/hpke.rs
> +    // Clippy can't "see" the `crypto-debug`-gated code above.
🙄

2023-03-15 16:12 UTC, franziskuskiefer commented on openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
> +            if ciphersuite != Ciphersuite::MLS_128_DHKEMP256_AES128GCM_SHA256_P256 {
Can you file an issue to move this into the crypto provider?

2023-03-15 17:45 UTC, merged