interop: Add some fixes to interop runner + chore.
openmls/openmls pull request #1348
Opened 2023-04-13 12:48 UTC by duesee

This PR improves the readability of the interop runner, improves the logging, adjusts AD, and adjusts the config so that the interop scenarios can pass. It is a bit difficult to review due to some renamings. I think these are an improvement but could understand if we want to revert.

This PR is a basis for the next ones that implement support for PSK, external join, and fix a transcript hash error. So, I hope it is one of the last PRs in this series.

2023-04-14 12:23 UTC, franziskuskiefer requested changes
Thanks, the trait changed. This needs the `free` function to compile again.

2023-04-14 12:23 UTC, franziskuskiefer commented on interop_client/Cargo.toml
> +tracing = "0.1.37"
```suggestion
tracing = "0.1"
```

2023-04-14 12:23 UTC, franziskuskiefer commented on interop_client/src/main.rs
> +        // trace!("   proposal: {proposal:#x?}");
remove commented code.

2023-04-14 12:23 UTC, franziskuskiefer commented on interop_client/src/main.rs
>          // TODO #692: The interop client cannot process these proposals yet.
Can this be resolved?

2023-04-17 09:59 UTC, duesee commented on interop_client/src/main.rs
>          // TODO #692: The interop client cannot process these proposals yet.
It will in the next PR.

2023-04-17 10:04 UTC, duesee commented
The last commit makes it very obvious that we probably want to rethink the default config values (or refactor the test runner). But I think we should not delay this more and refactor later.

2023-04-17 10:06 UTC, franziskuskiefer approved these changes
Thanks, lets get this in

2023-04-17 10:24 UTC, merged