fix: Regression on setting KeyPackage lifetimes
openmls/openmls pull request #1372
Opened 2023-04-27 10:23 UTC by OtaK

Hi!

While testing we found an API regression: It is no longer possible to set a lifetime/expiration for a KeyPackage while it was possible in 0.4.x.

This PR moves the `lifetime.rs` file within the `key_package` module, exposing it publicly, and adds the proper methods on the builder to use it.

2023-05-04 15:14 UTC, raphaelrobert requested changes
Good catch, just one nit.

2023-05-10 09:37 UTC, OtaK commented on openmls/src/key_packages/mod.rs
> +    #[allow(clippy::too_many_arguments)]
There's already a KeyPackageBuilder (modified a bit below in this PR) - The `create` method is internal and the entrypoint for the `KeyPackageBuilder` -> `KeyPackage` transition.

2023-05-11 12:41 UTC, OtaK commented
Rebased on top of current `main` branch.

@raphaelrobert I answered your review - I do think this is fine as-is as once again, I'd prefer not to cause deep structural changes on a simple regression fix, and the `KeyPackageBuilder` exists and has been modified accordingly.

2023-05-13 14:19 UTC, raphaelrobert approved these changes
Sorry, missed your comment, this is good to go after a rebase (you didn't give us the right to do).

2023-05-15 08:28 UTC, merged