Derive TlsDeserializeBytes for publicly exposed structs
openmls/openmls pull request #1442
Opened 2023-09-27 09:38 UTC by kkohbrok

2023-10-27 10:59 UTC, franziskuskiefer requested changes
I didn't look at everything yet, but all the `as tls_codec::Deserialize` casts seem pretty ugly. You could change the return value instead to tell the compiler which version you want.
But I think that's the other question. Why do you want to use the Bytes version for `MlsMessageIn`?

2023-10-27 10:59 UTC, franziskuskiefer commented on openmls/src/group/core_group/kat_passive_client.rs
> +        <RatchetTreeIn as tls_codec::Deserialize>::tls_deserialize_exact(bytes.0.as_slice())
I don't think these changes are needed ...

2023-10-27 10:59 UTC, franziskuskiefer commented on openmls/src/group/core_group/kat_welcome.rs
> +            <MlsMessageIn as tls_codec::Deserialize>::tls_deserialize_exact(
Same here, these should be unnecessary.

2024-01-05 14:48 UTC, kkohbrok commented
Closing in favor of #1468.

2024-01-05 14:48 UTC, closed without merging