Fix validation bug
openmls/openmls pull request #1491
Opened 2024-02-05 13:50 UTC by keks

This PR addresses issue #1487. The problem is that currently the list of extensions in a `GroupContextExtensions` proposal is compared against the capabilities of the current members. Instead, it needs to

1. check that the `RequiredCapabilities` of the group are satisfied by all members of the group
2. check that the types of all extensions in the proposal are in the `RequiredCapabilities`.

This PR also adds a method on the `RequiredCapabilitiesExtension` for checking whether an extension type is supported. This is needed because the extension types defined in the RFC are supported implicitly, so we also have to compare against the defaults. The defaults are defined close to the `Capabilities` struct and used to be private to these modules. I made the one for extension types `pub(crate)` so I can check against it.

Finally, I haven't written tests for this, yet. It seems this behaviour was barely tested before, as [the tests](https://github.com/openmls/openmls/blob/5052cbef2731214911ba69ea5a12e7a64481f45c/openmls/src/group/core_group/test_proposals.rs#L524-L540) seem to be commented out already. This is already tracked in #1130.

How do you all feel about merging this as-is and fixing the tests later (and opening an issue for it, of course)?

Fixes #1487

2024-02-05 17:31 UTC, raphaelrobert commented
What is the rationale behind skipping the tests?

Unless this is a blocker for something else or the test cannot be re-enabled without major refactoring (which then should have its own issue) there should be tests for validation checks.

2024-02-06 09:06 UTC, keks commented
The problem I am facing is that the validation bug was around the capabilities of the parties, which the current test functions do not really allow me to set. I would somehow get Alice's and Bob's capabilities into `setup_client`, which then pass it into the `KeyPackageBundle::new` which then would have to add it to the `KeyPackageBuilder`. As far as I can tell, only the last piece of that chain is implemented currently.

I think this does require some refactoring around how we can set up clients in tests. But right now I am not sure what the best way would be - `KeyPackageBundle::new` is a test helper function, and writing a builder for it seems somewhat overkill. And it's still not clear how to expose that functionality to `setup_client` -- maybe it could take a closure that performs operations on the builder. However, I think think these are changes that warrant their own issue and PR.

2024-02-08 16:01 UTC, raphaelrobert requested changes
Thanks for catching this. According to the spec there's also another place where this should be checked: when a new member is added.
>  For new members, support for required capabilities is enforced by existing members during the application of Add commits. 

Did you check that we do the right thing there?

Otherwise we need more comments.

2024-02-13 13:01 UTC, keks commented
Thank you for the review @raphaelrobert! I have added some more comments and tried making the code more readable in general, by not handling the iterator directly, but instead looping over it.

> Did you check that we do the right thing there?

Yes, that is checked here: https://github.com/openmls/openmls/blob/main/openmls/src/group/public_group/validation.rs#L307-L316

2024-02-13 13:24 UTC, raphaelrobert commented on openmls/src/group/public_group/validation.rs
> +            // There may only be one group context extionsion proposal. Return an error if there are more
```suggestion
            // There must at most be one group context extionsion proposal. Return an error if there are more
```

2024-02-13 13:26 UTC, raphaelrobert commented on openmls/src/group/public_group/validation.rs
> +            // There may only be one group context extionsion proposal. Return an error if there are more
```suggestion
            // There may only be one group context extension proposal. Return an error if there are more
```

2024-02-13 13:27 UTC, raphaelrobert commented on openmls/src/group/public_group/validation.rs
> +                            // need to chec that these are satisfied for all existing members of the group.
```suggestion
                            // need to check that these are satisfied for all existing members of the group.
```

2024-02-13 13:34 UTC, raphaelrobert requested changes
Thanks, just some nits in the comments

2024-02-13 13:34 UTC, raphaelrobert commented on openmls/src/group/public_group/validation.rs
> +                    // Make sure that all other extensions are know to be supported, by checking
```suggestion
                    // Make sure that all other extensions are known to be supported, by checking
```

2024-02-13 13:34 UTC, raphaelrobert commented on openmls/src/group/public_group/validation.rs
> +                    // that they are required to be supported by the required capabilities.
```suggestion
                    // that they are included in the required capabilities.
```

2024-02-13 13:34 UTC, raphaelrobert commented on openmls/src/group/public_group/validation.rs
> +        //}
Leftover?

2024-02-13 14:00 UTC, keks commented on openmls/src/group/public_group/validation.rs
> +        //}
Oops!

2024-02-13 14:02 UTC, raphaelrobert approved these changes

2024-02-13 14:49 UTC, merged