Check for last resort in core_group/new_from_welcome
openmls/openmls pull request #1503
Opened 2024-02-18 17:06 UTC by josephlukefahr

This PR just copies the logic in group::MlsGroup::new_from_welcome(...), which checks for last resort extension in keypackage, to group::CoreGroup::new_from_welcome(...).

2024-02-19 07:11 UTC, kkohbrok commented
Thanks for the PR! It looks like it solves the issue. To confirm that it does and to ensure we don't run into this sort of thing in the future, would you be so kind as to add a simple test? You can add the test to `mls_group/test_mls_group.rs`, where you can find inspiration on how to set up the test as well. I think it's better to have the test at the `MlsGroup` (rather than the `CoreGroup`) level, since we're likely to move all provider access to `MlsGroup` level eventually anyway (see #1207).

2024-02-19 07:12 UTC, kkohbrok requested changes
Thanks for the PR! It looks like it solves the issue. To confirm that it does and to ensure we don't run into this sort of thing in the future, would you be so kind as to add a simple test? You can add the test to `mls_group/test_mls_group.rs`, where you can find inspiration on how to set up the test as well. I think it's better to have the test at the `MlsGroup` (rather than the `CoreGroup`) level, since we're likely to move all provider access to `MlsGroup` level eventually anyway (see #1207).

(Also you'll have to run `cargo fmt` on the code before we can merge.)

2024-02-19 07:13 UTC, kkohbrok commented on openmls/src/group/core_group/new_from_welcome.rs
> +        // key store, but only if it doesn't have a last resort extension.
Could you change the text here (and in the debug log entry below) to indicate that this is about the leaf encryption key pair and not the KeyPackage?

2024-02-19 17:43 UTC, josephlukefahr commented
See 050d330 for the test.  Open to feedback/guidance on a more robust test procedure for this case.

2024-02-19 17:44 UTC, josephlukefahr commented
See 4253a26 for the `cargo fmt` changes.

2024-02-20 06:51 UTC, kkohbrok approved these changes
Thanks for adding the test and making the requested changes! This looks good to me, but clippy has a few complaints. Once you sort those out we can get this merged.

2024-02-20 06:51 UTC, kkohbrok commented on openmls/src/group/core_group/new_from_welcome.rs
> +        // key store, but only if it doesn't have a last resort extension.
Thanks!

2024-02-20 09:10 UTC, kkohbrok requested changes
Sorry, one last thing: Could you add an entry to the changelog indicating that this bug was fixed? You can find it in CHANGELOG.md.

2024-02-20 18:04 UTC, kkohbrok approved these changes
Excellent, thanks!

2024-02-21 16:35 UTC, merged