Detach the binary tree structure from the RatchetTree
openmls/openmls pull request #242
Opened 2020-12-03 10:23 UTC by kkohbrok

2020-12-09 18:01 UTC, raphaelrobert requested changes
Great start and nice abstraction!
I like the rule of commenting on why `.unwrap()` is safe to do, we should adopt that for other PRs as well.

2020-12-09 18:01 UTC, raphaelrobert commented on src/tree/treemath.rs
> +        x = parent(x, size).unwrap();
If the index is outside of the tree this will panic.

2020-12-10 06:41 UTC, kkohbrok commented on src/tree/binary_tree/mod.rs
> +        Ok(self.nodes.swap_remove(node_index.as_usize()))
I thought the rust-doc specifically said what is going on in `swap_remove`, i.e. it replaces the target element with the last element in the vector. So it doesn't technically preserve ordering, but in our case, it should be ok.

2020-12-10 06:52 UTC, kkohbrok commented
@raphaelrobert Thanks for all the great feedback! I talked to @franziskuskiefer yesterday to figure out if this is indeed the abstraction we want and in the end, we were both not too certain. We agreed to put this PR on hold and reconvene for a discussion on Monday. I'll still tackle all your comments, but probably not until then, as I might have to re-write/move chunks of this code anyway.

To summarize our discussion, Franziskus thought that the implementation was too specificly focused on an array-based binary tree. At the same time, the functions are not very generic, but rather pretty aligned with the needs of MLS.

After the discussion, I think the best solution would be to choose the functions provided by `treemath` as the binary tree interface and then write a more MLS specific second layer of abstraction which contains algorithms that handle more complex operations on the tree, that are somewhere between MLS-specific and somewhat binary-tree generic. For example, the algorithms could be blank-aware (which would allow us to pull more logic into that layer), but otherwise leave node-content specific operations to the higher layers by using closures.

2021-01-28 15:53 UTC, kkohbrok commented
This is pretty stale at this point. Closing in favour of #323.

2021-01-28 15:53 UTC, closed without merging