ignore PoC code for codecov
openmls/openmls pull request #253
Opened 2020-12-09 12:13 UTC by franziskuskiefer

2020-12-09 18:15 UTC, raphaelrobert requested changes

2020-12-09 18:15 UTC, raphaelrobert commented on codecov.yml
> +  - "delivery-service/**/*"  # ignore PoC DS server and lib
Let's also add the `cli` right away.

2020-12-10 07:59 UTC, kkohbrok submitted a review, later dismissed

2020-12-10 08:56 UTC, franziskuskiefer commented on codecov.yml
> +  - "delivery-service/**/*"  # ignore PoC DS server and lib
`cli` doesn't exist yet... but sure I can try to add it and see what happens 😉

2020-12-10 09:56 UTC, kkohbrok approved these changes

2020-12-10 10:07 UTC, merged