Redundant ciphertexts
openmls/openmls pull request #262
Opened 2020-12-14 13:07 UTC by raphaelrobert

This PR fixes #148.

The `resolve()` function is modified so that it accepts an exclusion list of `NodeIndex`es to filter out from the resolution.
The exclusion list is created in `apply_proposal()` when new members are added to a provisional tree and passed to the `resolve()` function.
There is a test to verify that the filtering works.

2020-12-14 13:45 UTC, franziskuskiefer requested changes
Thanks. Generally looks good to me. Only a couple nits.

2020-12-14 13:45 UTC, franziskuskiefer commented on src/tree/mod.rs
> +    ) -> Result<(bool, bool, InvitationList, HashSet<NodeIndex>), TreeError> {
These return values get pretty wild... at some point we should introduce structs to hold these complex values.

2020-12-14 13:45 UTC, franziskuskiefer commented on src/tree/mod.rs
> +            invitation_list
The question is though whether we really need to return this here. `new_leaves_indexes` can be computed from the return value `invitation_list`. It has to happen somewhere, it's just that there are already so many return values here.

2020-12-14 13:45 UTC, franziskuskiefer commented on src/tree/test_resolution.rs
> +            &[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30];
Can you add some description that tells me what exactly the test is (supposed to be) doing?

2020-12-14 13:45 UTC, franziskuskiefer commented on src/tree/mod.rs
> +                .collect::<Vec<NodeIndex>>(),
No need to collect.

2020-12-15 07:43 UTC, franziskuskiefer requested changes
Thanks, lgtm but we should skip the unnecessary collects.

2020-12-15 07:43 UTC, franziskuskiefer commented on src/tree/mod.rs
> +                .collect::<Vec<&NodeIndex>>(),
Still no need to `collect` 🙂 (you call `from_iter`).

2020-12-15 07:43 UTC, franziskuskiefer commented on src/tree/test_resolution.rs
> +                .collect::<Vec<&NodeIndex>>(),
Also no need to `collect` 🙂

2020-12-15 08:36 UTC, kkohbrok requested changes
Nice! Just a few nits, mostly documentation of `exclusion_list`.

Also, I'd much prefer `indices` over `indexes`, but I recognize that both are technically correct.

2020-12-15 08:36 UTC, kkohbrok commented on src/tree/mod.rs
> +        // Collect the new leaves indexes so we can filter them out in the resolution later
```suggestion
        // Collect the new leaves' indexes so we can filter them out in the resolution later
```

2020-12-15 08:36 UTC, kkohbrok commented on src/tree/mod.rs
> +    pub fn exclusion_list(&self) -> HashSet<&NodeIndex> {
Can you add some documentation on what this is meant to do? The name is not very explanatory.

2020-12-15 08:36 UTC, kkohbrok commented on src/group/mls_group/apply_commit.rs
> +                // Collect the new leaves indexes so we can filter them out in the resolution later
```suggestion
                // Collect the new leaves' indexes so we can filter them out in the resolution later.
```

2020-12-15 08:54 UTC, franziskuskiefer approved these changes
lgtm

2020-12-15 10:25 UTC, kkohbrok approved these changes
👍🏻

2020-12-15 10:26 UTC, merged