Fix codecov test coverage testing
openmls/openmls pull request #328
Opened 2021-02-01 08:33 UTC by kkohbrok

This PR moves the `ignore` section from `.github/workflows/coverage.yml` to a new file `.github/codecov.yml`.

According to the [documentation](https://docs.codecov.io/docs/codecov-yaml), this should fix codecov test coverage testing.

2021-02-01 09:03 UTC, raphaelrobert submitted a review, later dismissed
LGTM, let's see if it works

2021-02-01 10:14 UTC, franziskuskiefer requested changes

2021-02-01 10:14 UTC, franziskuskiefer commented on .github/codecov.yml
> +ignore:
This should go into the toplevel `codecov.yml`

2021-02-02 07:04 UTC, kkohbrok commented
We should probably wait with this one, as it appears to trigger an error within `cargo tarpaulin`. It's likely the same as this one: https://github.com/xd009642/tarpaulin/issues/655

2021-03-23 11:51 UTC, franziskuskiefer commented
The issue got fixed in nightly cargo. But now we have a linking issue 🙄

2021-03-23 13:00 UTC, kkohbrok commented
I think this would be the corresponding tarpaulin issue https://github.com/xd009642/tarpaulin/issues/517. I assume you switched to nightly, because it includes https://github.com/rust-lang/cargo/pull/9229? In the issue it seems the hope is that it also fixes the linker issue. But at least we're not the only ones having this problem.

Maybe it would be worth waiting for it to reach stable?

2021-03-24 13:24 UTC, franziskuskiefer commented
This was merged in #376

2021-03-24 13:24 UTC, closed without merging