TLS codec cleanup
openmls/openmls pull request #436
Opened 2021-07-07 11:15 UTC by franziskuskiefer

Sorry for the large PR but this had to happen in one go.
Please see the [tls_codec] crate for details on the tls codec implementation.

This PR removes the tls-codec and tls-codec-derive crates from the repository (they live in [tls_codec] now) as well as the codec module from the library.

Many structs and enum implement serialization through the derive macros `TlsSize`, `TlsSerialize`, and `TlsDeserialize`.
Others require manual implementation of the corresponding traits `Size`, `Serialize`, and `Deserialize`, providing the functions `tls_serialized_len`, `tls_serialize` and `tls_serialize_detached`, as well as `tls_deserialize`.
The implementation of [tls_codec] is more flexible than the old codec, taking `Read` and `Write` for (de)serializing, more efficient by directly encoding byte vectors, and allows us to delete a lot of code.

The treekem test vector is updated in this PR as well because it had some minor issues.

[tls_codec]: https://github.com/openmls/tls-codec/

2021-07-09 08:20 UTC, kkohbrok requested changes
Thanks for taking on this huge task! A few nits, but otherwise great work. Maybe we should at some point revisit the "config" approach for setting version and ciphersuite when deserialising `Secret`s. I think I'd sleep better if did the configuration on deserialization where possible.

One thing I noticed, that there were a lot of `FIXME: remove unwrap` throughout the code. Is that meant to happen still within this PR?

2021-07-09 08:36 UTC, franziskuskiefer reviewed
> One thing I noticed, that there were a lot of FIXME: remove unwrap throughout the code. Is that meant to happen still within this PR?

No, they are just markers. I filed #438 to tackle this.

2021-07-09 08:36 UTC, franziskuskiefer commented on openmls/src/lib.rs
> +// TODO: add group_context.serialized again
Ah, I forgot to remove them... That's just a todo list that's done 😳

2021-07-09 08:36 UTC, franziskuskiefer commented on openmls/src/key_packages/mod.rs
> +        // FIXME: remove unwrap
#438

2021-07-09 08:36 UTC, franziskuskiefer commented on openmls/src/credentials/errors.rs
> +use tls_codec::Error as TlsError;
I have no opinions on the alias here. I made it `TlsCodecError`.

2021-07-09 08:36 UTC, franziskuskiefer commented on openmls/src/ciphersuite/codec.rs
> +        CiphersuiteName::MLS10_128_DHKEMP256_AES128GCM_SHA256_P256.tls_serialized_len()
The function is not static, so it must be called on an object. The other option would be to manually write the value which is not much better 🤷🏻

2021-07-09 11:36 UTC, kkohbrok submitted a review, later dismissed
Thanks for addressing my comments! 🚢 it!

2021-07-12 06:35 UTC, kkohbrok approved these changes

2021-07-12 11:08 UTC, merged