Introduce type system for validation
openmls/openmls pull request #545
Opened 2021-11-14 17:01 UTC by raphaelrobert

This PR is a follow-up PR towards implementing validation. It does not yet contain tests, which will be tackled with #525, #527, and #528.

 - Use strict types for the different stages of message validation
 - This is based on `VerifiableMlsPlaintext` but supersedes its purpose somewhat. We can debate whether `VerifiableMlsPlaintext` is still needed in the future.
 - Move MlsMessageIn & MlsMessageOut to `framing` and add serialization/deserialization for these types
 - Said serialization now looks at the first byte of the serialized data to determine the wire_format, instead of prepending a duplicate
 - Improvement: it membership tags are now also verified for Commit messages (probably more will be discovered with better testing)

2021-11-15 08:19 UTC, kkohbrok commented
Just did a rough pass for now. One thing I would suggest from a structural standpoint is to put more of the logic that is now in functions like `parse_message` in functions that are part of the implementation of the individual datatypes. So that one can call ```
let decrypted_message = DecryptedMessage::from_inbound_message(message, ...)?;
```
On the one hand, that requires passing potentially unneeded information (e.g. decryption keys even if the message is a plaintext), but on the other hand, we get rid of some of the complexity. What do you think?

2021-11-15 08:52 UTC, raphaelrobert commented
> Just did a rough pass for now. One thing I would suggest from a structural standpoint is to put more of the logic that is now in functions like `parse_message` in functions that are part of the implementation of the individual datatypes. So that one can call
> 
> ```
> let decrypted_message = DecryptedMessage::from_inbound_message(message, ...)?;
> ```
> 
> On the one hand, that requires passing potentially unneeded information (e.g. decryption keys even if the message is a plaintext), but on the other hand, we get rid of some of the complexity. What do you think?

I think I can move some of the checks into the new types. Regarding the substantial differences in the arguments, I would prefer to have two separate functions to create a `DecryptedMessage`.

2021-11-15 09:19 UTC, kkohbrok commented
Fair enough. The match statements that error out in case you call the function with the wrong enum always feel very ugly to me, but I understand that the unnecessary arguments are also not pretty.

2021-11-15 11:30 UTC, franziskuskiefer commented
> The match statements that error out in case you call the function with the wrong enum always feel very ugly to me

These should probably be `if let ...` instead of `match`.

2021-11-16 15:52 UTC, kkohbrok requested changes
A few nitpicks, but otherwise looks good!

2021-11-16 15:52 UTC, kkohbrok commented on openmls/src/framing/validation.rs
> +//! DecryptedMessage
This state is not really visible to the outside, though, is it? Or at least it's not the return type of `parse_message`.

2021-11-16 15:52 UTC, kkohbrok commented on openmls/src/framing/validation.rs
> +        match signature_key {
Sorry to nitpick here, but all this matching seems a bit much. Maybe something like this?
```
        let verified_member_message = if let Some(signature_public_key) = signature_key {
            self.plaintext
                .verify_with_key(backend, signature_public_key)
        } else {
            self.plaintext.verify(backend, &self.credential)
        }
        .map(|plaintext| VerifiedMemberMessage { plaintext })?;
        Ok(verified_member_message)
```

2021-11-16 15:52 UTC, kkohbrok commented on openmls/src/group/managed_group/validation.rs
> +                    MlsPlaintextContentType::Proposal(_proposal) => {
Would it be worth revisiting the constructors for StagedProposal and `stage_commit` to take the content instead of the whole plaintext?

2021-11-16 15:52 UTC, kkohbrok commented on openmls/src/group/managed_group/validation.rs
> +                match signature_key {
Nitpicking again: Even though it makes returning the error slightly less explicit: I think I'd use an `ok_or` here. Or maybe an `if let`.

2021-11-17 09:48 UTC, raphaelrobert commented on openmls/src/framing/validation.rs
> +                return Err(ValidationError::LibraryError);
Decrypting an `MlsCiphertext` would fail if it wasn't encrypted by a member, i.e. we wouldn't be able to fetch the right key material for decryption.

2021-11-17 11:14 UTC, kkohbrok requested changes
Almost there! Just a few more comments on the docs.

2021-11-17 11:14 UTC, kkohbrok commented on openmls/src/framing/validation.rs
> +                return Err(ValidationError::LibraryError);
I see, thanks!

2021-11-17 11:14 UTC, kkohbrok commented on openmls/src/framing/validation.rs
> +    pub(crate) fn from_inbound_plaintext(
Thanks for adding docs on the structs! The functions still don't have documentation. The functions aren't hugely complex, but having at least a brief sentence what they do would be nice. Especially for the `pub` functions.

2021-11-17 11:14 UTC, kkohbrok commented on openmls/src/framing/validation.rs
> +/// Contains an [VerifiableMlsPlaintext] and a [Credential] if it is a member message.
`Contains an [VerifiableMlsPlaintext]` -> `Contains a [VerifiableMlsPlaintext]`

2021-11-17 11:14 UTC, kkohbrok commented on openmls/src/framing/validation.rs
> +/// Checks the presence of the membership tag and confirmation tag.
Some of this feels like it should be documentation for the functions that are part of this struct's implementation. For example, `... it attempts to decrypt the ciphertext`. What is it? Same for the last sentence.

2021-11-17 15:18 UTC, raphaelrobert commented
> Almost there! Just a few more comments on the docs.

The plan is to add more explicit documentation about the different checks once the tests are there.

2021-11-17 15:49 UTC, kkohbrok approved these changes
Perfect, thanks!

2021-11-17 15:50 UTC, merged