Continue validation tests
openmls/openmls pull request #571
Opened 2021-11-23 19:28 UTC by raphaelrobert

This PR continues the validation tests that were started in #560.
Fixes #527.

Note that the tests are all carried out on the `ManagedGroup`, which now directly passes it on t the corresponding function `MlsGroup`, so that both are being tested.

2021-11-24 09:30 UTC, kkohbrok requested changes
Nice to see the validation in action 🙂. So far, I can only see negative tests. We kind of do positive tests implicitly through the scenarios and the test vectors, but it would be nice to have an explicit positive test alongside each negative test here as well.

2021-11-24 09:30 UTC, kkohbrok commented on openmls/src/group/tests/test_validation.rs
> +    plaintext.set_epoch(GroupEpoch(100));
Since the Epoch can be both too high and too low, it would be nice to have one test case for each.

2021-11-24 10:10 UTC, raphaelrobert commented
> Nice to see the validation in action 🙂. So far, I can only see negative tests. We kind of do positive tests implicitly through the scenarios and the test vectors, but it would be nice to have an explicit positive test alongside each negative test here as well.

Thanks for the review! I'm usually all for positive tests as well. In these tests however I take the same Commit message most of the time and I manipulate it. The positive test would be that the Commit message can be parsed and processed. I can add that, but I wonder how beneficial that is.

2021-11-24 11:06 UTC, kkohbrok commented
I'd prefer adding positive tests, just to be methodical. Can't you clone the commit before manipulation and process it after processing the manipulated message has failed? That would to the trick and I would imagine that that's relatively low-effort.

2021-11-29 07:11 UTC, kkohbrok approved these changes
Thanks a bunch! Let's get it in 🙂

2021-11-29 09:38 UTC, merged