[722][723] Fixed 2 issues on OpenMls Repo
openmls/openmls pull request #724
Opened 2022-01-22 00:21 UTC by pulkitkothari

https://github.com/openmls/openmls/issues/722
https://github.com/openmls/openmls/issues/723

2022-01-22 12:52 UTC, raphaelrobert requested changes
Thanks for the PR! Could make two separate PRs, one for each issue? That way we can discuss this separately.

2022-01-22 20:02 UTC, pulkitkothari commented
@raphaelrobert  Done this diff just have one bug fix.

2022-01-22 21:02 UTC, raphaelrobert requested changes
Thanks, just one nit to make it more rusty.

2022-01-22 21:02 UTC, raphaelrobert commented on openmls/src/group/mls_group/mod.rs
> +        return self.group.context().epoch();
```suggestion
        self.group.context().epoch()
```

2022-01-23 07:17 UTC, pulkitkothari commented
Still getting used to rust ;p thanks for the review and prompt replies.

2022-01-23 12:42 UTC, raphaelrobert approved these changes
Thanks!

2022-01-23 12:42 UTC, merged