Add missing doc to public API
openmls/openmls pull request #743
Opened 2022-01-29 20:04 UTC by raphaelrobert

This PR adds the missing documentation for the public API. It also does some minor renaming (`KeyID` has been renamed to `ExternalKeyID` in the spec at some point and we missed it) and restricts the visibility here and there. There are no other code changes.

2022-01-31 10:13 UTC, kkohbrok requested changes
Thanks for tackling this!

As noted in the comments, I'm not sure that the text from the spec makes good documentation for our code. It helps to provide a link, but a lot of the text is not really relevant for the consumer. For example in places where our code makes sure certain properties hold that we don't even expose to the consumer.

Also, while I understand that some of the enums are somewhat self-explanatory, I still think that adding a brief comment would be helpful.

2022-01-31 10:13 UTC, kkohbrok commented on openmls/src/key_packages/mod.rs
> +//! it is possible to pre-publish key packages that provide some public
```suggestion
//! it is necessary to pre-publish key packages that provide some public
```

2022-01-31 10:13 UTC, kkohbrok commented on openmls/src/key_packages/mod.rs
> +//! to the group asynchronously.A KeyPackage object specifies a ciphersuite
```suggestion
//! to the group asynchronously. A KeyPackage object specifies a ciphersuite
```

2022-01-31 10:13 UTC, kkohbrok commented on openmls/src/key_packages/mod.rs
> +//!  to support multiple ciphersuites.KeyPackages contain a public key chosen by the
```suggestion
//!  to support multiple ciphersuites. KeyPackages contain a public key chosen by the
```

2022-01-31 10:13 UTC, kkohbrok commented on openmls/src/key_packages/mod.rs
> +//! object among the set of KeyPackages created by this client.The value for
```suggestion
//! object among the set of KeyPackages created by this client. The value for
```

2022-01-31 10:13 UTC, kkohbrok commented on openmls/src/key_packages/mod.rs
> +//! defined by cipher_suite. The whole structure is signed using the client's
I don't think we offer a possibility to insert self-generated KeyPackages, so OpenMLS will ensure that most of these requirements are met. Do we still need to list them here?

2022-01-31 16:22 UTC, raphaelrobert commented on openmls/src/credentials/mod.rs
> +//! # Credentials
I changed the paragraph.

2022-01-31 16:23 UTC, raphaelrobert commented
> Thanks for tackling this!
> 
> As noted in the comments, I'm not sure that the text from the spec makes good documentation for our code. It helps to provide a link, but a lot of the text is not really relevant for the consumer. For example in places where our code makes sure certain properties hold that we don't even expose to the consumer.
> 
> Also, while I understand that some of the enums are somewhat self-explanatory, I still think that adding a brief comment would be helpful.

Regarding the enums: I skipped the documentation for those are come straight from the spec. All others are annotated.

2022-01-31 17:09 UTC, kkohbrok commented on openmls/src/credentials/mod.rs
> +//! # Credentials
Thanks!

2022-01-31 17:11 UTC, kkohbrok commented
What is the rationale for skipping the ones that come from the spec? Do we assume that devs are familiar with the spec and thus the documentation is not necessary?

2022-02-01 11:48 UTC, raphaelrobert commented
> What is the rationale for skipping the ones that come from the spec? Do we assume that devs are familiar with the spec and thus the documentation is not necessary?

I only skipped it on variants of self-explanatory enums, not on the enums themselves. Things like ciphersuites, extensions, etc. I can copy over stuff form the spec, but that's also not what you wanted as per you initial comment.

2022-02-01 14:24 UTC, kkohbrok approved these changes
Thanks for making the changes! Let's get this in, then.

2022-02-02 10:54 UTC, merged