Store old key package reference in MessagesSecretsStore
openmls/openmls pull request #746
Opened 2022-01-31 11:45 UTC by franziskuskiefer

The mechanism introduced in #563 to decrypt past epochs requires us to store key package references from the past epochs as well.
Since the sender is identified by its key package reference, which can change, this identifier needs to be stored for past epochs and used in lookups.

Fixes #705

2022-01-31 14:00 UTC, kkohbrok requested changes
Thanks for bringing this validation check back! For my understanding this looks good, with just a few comments.

2022-02-01 08:13 UTC, franziskuskiefer commented on openmls/src/group/core_group/mod.rs
> +            Ok((self.message_secrets_store.message_secrets_mut(), Vec::new()))
It doesn't matter what we return here as this is never used. If we're interested in the current epoch, we have the tree.

2022-02-01 08:13 UTC, franziskuskiefer commented on openmls/src/group/core_group/mod.rs
> +    pub(crate) fn message_secrets_and_leaves_mut<'secret, 'group: 'secret>(
Right, there's no other place where we can easily do this. Having all the logic for handling past epochs in one place is also nice.

2022-02-01 08:46 UTC, kkohbrok commented on openmls/src/group/core_group/mod.rs
> +            Ok((self.message_secrets_store.message_secrets_mut(), Vec::new()))
Fair enough, but then that should at least be mentioned in the docs. Without any further information, I would assume from the name of the function that I get the message secrets and the leaves from the given epoch. It's not really clear that the current epoch is a special case.

2022-02-01 15:56 UTC, kkohbrok submitted a review, later dismissed
Thanks! Let's get this in!

2022-02-01 17:25 UTC, raphaelrobert approved these changes
Thanks! I had to look at this a bit longer because of the validation logic (see me inline comment).

2022-02-01 18:45 UTC, franziskuskiefer commented on openmls/src/framing/validation.rs
> +    pub fn credential(
👍🏻 I filed #754 and put in the validation meta issue to have a note for potential follow ups.

2022-02-02 09:16 UTC, raphaelrobert approved these changes
Thanks!

2022-02-02 10:02 UTC, kkohbrok approved these changes

2022-02-02 10:04 UTC, merged