[FixUp] join_by_external_commit does not need to request proposal store and aad
openmls/openmls pull request #890
Opened 2022-04-22 20:58 UTC by pulkitkothari

ProposalStore::new() method visibility is for crate only, so no one is the application can call this method which is required by join_by_external_commit method.
Also there are no public methods which allow temporary proposal to be stored proposals that are received from the DS in between two commit messages by the application before creating group.

https://github.com/openmls/openmls/blob/main/openmls/src/group/core_group/proposals.rs#L27

2022-04-22 21:00 UTC, pulkitkothari commented on openmls/src/group/mls_group/creation.rs
> +            .proposal_store(&ProposalStore::new())
We may use this same proposal store instance in MlsGroup constructor as well.

2022-04-22 21:23 UTC, pulkitkothari commented on openmls/src/group/mls_group/creation.rs
> +        let proposal_store = ProposalStore::new();
We may use this same proposal store instance in MlsGroup constructor as well.

2022-04-25 18:29 UTC, raphaelrobert requested changes
Thanks for the PR! This makes sense and it is also in line with the spec:

> The Commit MUST NOT include any proposals by reference, since an external joiner cannot determine the validity of proposals sent within the group

Technically this is a breaking API change, but since the API wasn't usable at all it is really just a fix.

Could you please make an entry in the `CHANGELOG.md` file?
Can you add a section called "Changed" under `[Unreleased]` and mention the fix in a bullet point?

2022-04-25 19:39 UTC, raphaelrobert approved these changes
Thanks!

2022-04-25 19:39 UTC, merged