Removed unrequired mutable borrows
openmls/openmls pull request #907
Opened 2022-07-28 10:42 UTC by beltram

Some mutable borrows were required in some methods, especially `process_unverified_message` whereas it was not required.
Removing them makes the methods intent clearer, helps working with borrow checker rules and could also have runtime advantages.

2022-07-28 15:09 UTC, raphaelrobert commented
I can review in more detail after vacation, but for now I see that it breaks tests and I think it might potentially invalidate Forward Secrecy.

2022-07-28 16:02 UTC, beltram commented
@raphaelrobert yes feel free to review when you are back.  
Failing tests are actually another issue (you will have exact same failure on main branch, it is unrelated to this PR). We found out test_vectors contain a KeyPackage with a lifetime extension expiring on the 13th of July 2022. We will hopefully have time to fix it and also merge it here as well.

2022-10-17 13:28 UTC, franziskuskiefer requested changes
Thanks for the PR.
Generally looks good to me. There are number of unrelated changes I don't understand where they are coming from or why they are in here.
Also, let's see if we can clean up a little more.

2022-10-17 13:28 UTC, franziskuskiefer commented on openmls/src/group/core_group/mod.rs
> +use log::{debug, trace};
Where are these changes coming from?

2022-10-17 14:18 UTC, beltram commented on openmls/src/group/core_group/mod.rs
> +    pub(crate) fn message_secrets_for_epoch<'secret, 'group: 'secret>(
Yes we do. It is used in other places which still require mutable borrow

2022-10-17 14:18 UTC, beltram commented on openmls/src/group/core_group/past_secrets.rs
> +    pub(crate) fn secrets_for_epoch(
No. Because it is used in `message_secrets_for_epoch`

2022-10-18 10:54 UTC, franziskuskiefer commented on openmls/src/ciphersuite/aead.rs
> +pub(crate) struct AeadNonce([u8; NONCE_BYTES]);
I wouldn't call it zero cost abstraction. But let's leave it in.

2022-10-18 12:55 UTC, beltram commented
All remaining comments addressed

2022-10-19 10:48 UTC, franziskuskiefer approved these changes

2022-10-19 11:27 UTC, merged